name: Build Library

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Push to dist branch
        run: |
          # Set up Git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create dist branch if it doesn't exist
          git branch -D dist || true
          git switch -c dist

          # Remove all files except dist folder and package.json
          find . -maxdepth 1 ! -name 'dist' ! -name 'package.json' ! -name '.' ! -name .git | xargs rm -rf

          # Commit and push changes
          git add .
          git commit -m "Deploy to dist branch"
          git push origin dist --force
